name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "src/apps/team-management/api/**"
      - "src/contexts/shared/core/**"
      - "src/contexts/team-management/**"
  pull_request:
    branches: [main]
    types: [opened,synchronize,reopened]
    paths:
      - "src/apps/team-management/api/**"
      - "src/contexts/shared/core/**"
      - "src/contexts/team-management/**"
  workflow_dispatch:
jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16.14.2'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint:team:back
  sonar:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ github.token }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: src/apps/team-management/api
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16.14.2'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:team:back
  test:
    needs: [lint, build, sonar]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16.14.2'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:team:back:unit
  e2e:
    needs: [lint, build, sonar]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16.14.2'
      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:team:back:e2e
          start: npm run start:team:back:dev
          wait-on: 'http://localhost:3000/api'
  deploy:
    needs: [test, e2e]
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16.14.2'
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
